#!/usr/bin/env python

# vim:ft=python

import sys
import os
import traceback

try:
    from modules import posthandler
except ImportError:
    logme = ">>> ImportError"
    fh = open("/home/torrent/pyrt/pyrt.log", "a")
    fh.write("\n%s\n" % logme)
    fh.close()

if __name__ == "__main__":
    try:
        filepath = os.path.join("/home/torrent/torrents/downloading/", os.path.basename(sys.argv[1]))
        if not os.path.exists(filepath):
            logme = ">>> posthook: <%s> doesn't exist" % filepath
        else:
            PH = posthandler.PostHandler()
            logout = PH.checkNewFile(filepath)
            if not logout:
                logme = ">>> posthook: <%s> not in filter list" % os.path.basename(filepath)
            else:
                logme = logout
    except:
        logme += "\n%s" % traceback.format_exc()

    fh = open("/home/torrent/pyrt/pyrt.log", "a")
    fh.write("\n%s\n" % logme)
    fh.close()
